# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aallali <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/07 20:09:26 by aallali           #+#    #+#              #
#    Updated: 2018/10/08 01:34:39 by aallali          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
all : $(NAME)
$(NAME) :
	gcc -Wall -Wextra -Werror -o $(NAME) main.c
clean :
	rm -f *.o
fclean : clean
	rm -f $(NAME)
